default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= Rails.application.credentials.mysql_password %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: qrapp_development

test:
  <<: *default
  database: qrapp_test

production:
  <<: *default
  database: qrapp_production
